// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.924
package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "github.com/pipdaniels/geochem-agent/internal/web/templates/layout"

func Signup() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"auth-page\"><div class=\"auth-container\"><div class=\"auth-header\"><h1>Create Account</h1><p>Start your geochemical exploration journey</p></div><form action=\"/signup\" method=\"POST\" class=\"auth-form\"><div class=\"form-group\"><label for=\"orgName\">Organization Name</label> <input type=\"text\" id=\"orgName\" name=\"org_name\" required placeholder=\"My Mining Corp\"></div><div class=\"form-group\"><label for=\"email\">Email Address</label> <input type=\"email\" id=\"email\" name=\"email\" required placeholder=\"you@company.com\"></div><div class=\"form-group\"><label for=\"password\">Password</label> <input type=\"password\" id=\"password\" name=\"password\" required minlength=\"8\"></div><div class=\"form-group\"><label for=\"confirmPassword\">Confirm Password</label> <input type=\"password\" id=\"confirmPassword\" name=\"confirm_password\" required minlength=\"8\"></div><div class=\"form-group\"><label for=\"passkey\">Invite Passkey</label> <input type=\"text\" id=\"passkey\" name=\"passkey\" required placeholder=\"Enter invite code\"> <small class=\"form-hint\">Required for beta access</small></div><div class=\"form-group checkbox\"><label><input type=\"checkbox\" name=\"terms\" required> I accept the Terms of Service and Privacy Policy</label></div><button type=\"submit\" class=\"btn btn-primary btn-block\">Create Account</button><div class=\"auth-footer\"><p>Already have an account? <a href=\"/signin\">Sign In</a></p></div></form></div></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = layout.Base("Sign Up - GeoAgent").Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
